version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: weekly
    groups:
      aws-sdk:
        patterns: ["@aws-sdk/*"]
  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
    ignore:
      - dependency-name: react-scripts
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /server
    schedule:
      interval: monthly
